name: Coverage

on:
  pull_request:
    branches:
    - master

jobs:
  coverage:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm ci, build, and coverage testing
      run: |
        npm ci
        npm run css:build
        npm run coverage
        npm run coverage:check
      env:
        CI: true

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        parallel: true
        github-token: ${{ secrets.github_token }}

    - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true

    - name: generate html report
      run: npm run coverage:generate-html-report

    - name: upload html report as artifact
      uses: actions/upload-artifact@master
      with:
        name: coverage-report
        path: docs/coverage
